package com.CRUDAppTests;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertThat;
import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.PageFactory;

public class SeleniumTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    driver.navigate().to("http://localhost:8080/CRUDAppTheSecound/");
  }

  @Test
  public void dDTest() {}

  @Test
  public void testCharacterCreationPage() {
    indexPageTest indexTest = new indexPageTest();
    PageFactory.initElements(driver, indexTest);
    indexTest.enterUsername("Username");
    indexTest.chooseClass();
    assertThat(
        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(),
        is("Username"));
    assertThat(
        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")).getText(),
        is("Bowman"));
    driver.findElement(By.cssSelector("td:nth-child(7) > .btn")).click();
  }

  @Test
  public void testFightPage() {
    driver.navigate().to("http://localhost:8080/CRUDAppTheSecound/fightPage");
    assertThat(driver.findElement(By.xpath("//table/tbody/tr[3]/td[2]")).getText(), is("Monster"));
    assertFalse(driver.findElement(By.id("monsterName")).getSize() == null);
  }

  @Test
  public void testModifyUser() {
    driver.navigate().to("http://localhost:8080/CRUDAppTheSecound/modifyPage");
    RenamePage renamePage = new RenamePage();
    PageFactory.initElements(driver, renamePage);
    renamePage.renameUsername("Pesho");
    assertThat(
        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(),
        is("Pesho"));
  }

  @Test
  public void testfighPhase() {
    driver.navigate().to("http://localhost:8080/CRUDAppTheSecound/fightPage?");
    FightPage fightPage = new FightPage();
    PageFactory.initElements(driver, fightPage);
    fightPage.checkText();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
}
